[phases.setup]
nixPkgs = ["python312", "bash"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p webapp/logs", "mkdir -p models/trained"]

[start]
cmd = "bash start.sh"
